# Refer to https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: IceRunner Kotlin CI

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "!.github/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "!.github/**"
      - ".github/workflows/**"

jobs:
  # Job that builds the plugin JAR
  build:
    runs-on: ubuntu-latest
    steps:
      # Copies the repository content
      - uses: actions/checkout@v4

      # Sets up the java version and enables Maven caching strategy
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
          cache: gradle

      - name: Run the Gradle build script
        run: "./gradlew build"

  # Running the plugin's tests
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # Copies the repository content
      - uses: actions/checkout@v4

      # Sets up the java version and enables Maven caching strategy
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
          cache: gradle

      - name: Run the Gradle test script
        run: "./gradlew test"