# Refer to https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: IceRunner Kotlin CI

permissions:
  id-token: write
  attestations: write

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  # Job that builds the plugin JAR
  check:
    runs-on: ubuntu-latest
    steps:
      # Copies the repository content
      - uses: actions/checkout@v6

      # Sets up the java version and enables Maven caching strategy
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
          cache: gradle

      - name: Run the Gradle build script
        run: "./gradlew check"

  # Running the plugin's tests
  doc:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      # Copies the repository content
      - uses: actions/checkout@v6

      # Sets up the java version and enables Maven caching strategy
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
          cache: gradle

      - name: Run the Gradle doc build script
        run: "./gradlew dokkaGeneratePublicationHtml"

      - name: Archive generated fat JAR file
        uses: actions/upload-artifact@v5
        with:
          name: 'IceRunner-Docs'
          path: build/dokka/html/

  # Running the plugin's tests
  build:
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      # Copies the repository content
      - uses: actions/checkout@v6

      # Sets up the java version and enables Maven caching strategy
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64
          cache: gradle

      - name: Run the Gradle Fat JAR build script
        run: "./gradlew shadowJar"

      - name: Archive generated fat JAR file
        uses: actions/upload-artifact@v5
        with:
          name: 'IceRunner-${{ github.sha }}.jar'
          path: artifacts/IceRunner.jar

      - name: Attest build provenance of said artifact
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: artifacts/IceRunner.jar